# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.19.8'

    - uses: arduino/setup-protoc@v2

    - run: go install google.golang.org/protobuf/cmd/protoc-gen-go@v1.28
    - run: go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@v1.2
    - run: 'export PATH="$PATH:$(go env GOPATH)/bin"'

    - name: Build
      run: mkdir -p build && cd build && make -C .. all

    - name: Test
      run: go test -v ./...

    - name: Format
      run: if [ "$(gofmt -s -l server client | wc -l)" -gt 0 ]; then exit 1; fi
